version: 2.1
workflows:
  on_commit:
    jobs:
      doc_publish:
        filter:
          branches:
            only: main
        docker:
          - image: cimg/python:3.12.1
        steps:
          - checkout
          - run: |
            pip install -r requirements.txt
            mkdocs
            # TODO: Setup gh auth?
            mkdocs gh-deploy
  