version: 2.1
jobs:
  doc_publish:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          mkdocs
          # TODO: Setup gh auth?
          mkdocs gh-deploy

workflows:
  on_commit:
    jobs:
      - doc_publish:
          filters:
            branches:
              only: main
